export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR'

export const TOGGLE_DEVICE = 'TOGGLE_DEVICE'

export const SET_SIZE = 'SET_SIZE'

export const ADD_ERROR_LOG = 'ADD_ERROR_LOG'

export const CLEAR_ERROR_LOG = 'CLEAR_ERROR_LOG'

export const SET_ROUTES = 'SET_ROUTES'
export const CHANGE_SETTING = 'CHANGE_SETTING'
export const ADD_VISITED_VIEW = 'ADD_VISITED_VIEW'
export const ADD_CACHED_VIEW = 'ADD_CACHED_VIEW'
export const DEL_VISITED_VIEW = 'DEL_VISITED_VIEW'
export const DEL_CACHED_VIEW = 'DEL_CACHED_VIEW'

export const DEL_OTHERS_VISITED_VIEWS = 'DEL_OTHERS_VISITED_VIEWS'
export const DEL_OTHERS_CACHED_VIEWS = 'DEL_OTHERS_CACHED_VIEWS'
export const DEL_ALL_VISITED_VIEWS = 'DEL_ALL_VISITED_VIEWS'
export const DEL_ALL_CACHED_VIEWS = 'DEL_ALL_CACHED_VIEWS'
export const UPDATE_VISITED_VIEW = 'UPDATE_VISITED_VIEW'

export const SET_TOKEN = 'SET_TOKEN'
export const SET_INTRODUCTION = 'SET_INTRODUCTION'
export const SET_NAME = 'SET_NAME'
export const SET_AVATAR = 'SET_AVATAR'
export const SET_ROLES = 'SET_ROLES'
